Force new version of transit-clj.
Using the version loaded by [com.datomic/client-cloud "0.8.78"],
the version of com.cognitect.transit.TransitFactory.writer with the
correct signature is missing, causing:

java.lang.NoSuchMethodError: 'com.cognitect.transit.Writer
com.cognitect.transit.TransitFactory.writer(com.cognitect.transit.TransitFactory$Format,
java.io.OutputStream, java.util.Map,
com.cognitect.transit.WriteHandler, java.util.function.Function)'